import React from 'react';
import './Terms.css';

const Terms = () => {
  const lastUpdated = "January 30, 2025";

  const sections = [
    {
      id: "acceptance",
      title: "Acceptance of Terms",
      content: `By downloading, installing, or using CrowmanCloud, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use CrowmanCloud.

These Terms constitute a legally binding agreement between you and CrowmanCloud, Inc. ("we," "us," or "our") regarding your use of the CrowmanCloud software application and related services.`
    },
    {
      id: "description",
      title: "Service Description",
      content: `CrowmanCloud is a local-first desktop application that provides cloud deployment analysis and recommendations. Our service includes:

• **Code Analysis**: Local analysis of your source code for cloud readiness
• **Security Scanning**: Detection of vulnerabilities and security issues
• **Cloud Recommendations**: Suggestions for AWS, Google Cloud, and Azure services
• **Cost Estimation**: Projected costs for recommended cloud services
• **Infrastructure Generation**: Automated creation of deployment configurations
• **Local Processing**: All analysis occurs on your local machine

CrowmanCloud operates entirely on your device and does not require uploading your source code to external servers.`
    },
    {
      id: "license",
      title: "License and Usage Rights",
      content: `Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to:

• **Install and Use**: Install CrowmanCloud on devices you own or control
• **Personal and Commercial Use**: Use CrowmanCloud for both personal and commercial projects
• **Multiple Installations**: Install on multiple devices for your use
• **Team Usage**: Use within your organization or team

**Restrictions**: You may not:
• Reverse engineer, decompile, or disassemble the software
• Distribute, sell, or sublicense CrowmanCloud
• Remove or modify copyright notices or proprietary markings
• Use CrowmanCloud for illegal or unauthorized purposes
• Attempt to circumvent security measures or access restrictions`
    },
    {
      id: "user-responsibilities",
      title: "User Responsibilities",
      content: `As a user of CrowmanCloud, you are responsible for:

**System Requirements**: Ensuring your system meets the minimum requirements for CrowmanCloud
**Data Backup**: Maintaining backups of your important data and projects
**Security**: Keeping your system secure and up-to-date
**Compliance**: Using CrowmanCloud in compliance with applicable laws and regulations
**Accurate Information**: Providing accurate information when contacting support

**Prohibited Uses**: You agree not to use CrowmanCloud to:
• Analyze code you do not have rights to analyze
• Violate any applicable laws or regulations
• Infringe on intellectual property rights of others
• Engage in any harmful or malicious activities
• Attempt to compromise the security of the software`
    },
    {
      id: "local-first",
      title: "Local-First Architecture and Data",
      content: `CrowmanCloud is designed with a local-first architecture:

**Your Code Remains Local**: Your source code is never transmitted to our servers or any third-party services. All analysis occurs entirely on your local machine.

**Local Data Storage**: Analysis results, configurations, and preferences are stored locally on your device.

**No Cloud Dependencies**: CrowmanCloud functions without requiring internet connectivity for core analysis features.

**Data Ownership**: You retain complete ownership and control of your code and analysis results.

**Privacy Protection**: Our local-first approach ensures maximum privacy and security for your intellectual property.`
    },
    {
      id: "intellectual-property",
      title: "Intellectual Property Rights",
      content: `**Our Rights**: CrowmanCloud, including its software, documentation, trademarks, and related materials, is owned by CrowmanCloud, Inc. and protected by intellectual property laws.

**Your Rights**: You retain all rights to your source code and projects analyzed by CrowmanCloud. We claim no ownership over your code or analysis results.

**Generated Content**: Infrastructure files and configurations generated by CrowmanCloud are provided for your use without restriction.

**Feedback**: Any feedback, suggestions, or ideas you provide about CrowmanCloud may be used by us without compensation or attribution.

**Third-Party Content**: CrowmanCloud may include third-party libraries and components, each subject to their respective licenses.`
    },
    {
      id: "updates",
      title: "Software Updates and Modifications",
      content: `**Automatic Updates**: CrowmanCloud may automatically download and install updates to improve functionality, security, and performance.

**Update Control**: You can control update preferences through the application settings.

**Service Modifications**: We reserve the right to modify, suspend, or discontinue any aspect of CrowmanCloud with reasonable notice.

**Compatibility**: We strive to maintain backward compatibility but cannot guarantee it across all updates.

**Beta Features**: Some features may be provided as beta or experimental functionality with additional terms.`
    },
    {
      id: "disclaimers",
      title: "Disclaimers and Limitations",
      content: `**"As Is" Basis**: CrowmanCloud is provided "as is" without warranties of any kind, express or implied.

**No Guarantees**: We do not guarantee that:
• CrowmanCloud will be error-free or uninterrupted
• Analysis results will be completely accurate
• Cost estimates will match actual cloud provider charges
• The software will meet your specific requirements

**Analysis Accuracy**: While we strive for accuracy, analysis results and recommendations are provided for informational purposes only.

**Third-Party Services**: We are not responsible for the accuracy of third-party cloud provider pricing or service information.

**System Compatibility**: We do not guarantee compatibility with all system configurations or third-party software.`
    },
    {
      id: "liability",
      title: "Limitation of Liability",
      content: `**Maximum Liability**: Our total liability to you for any claims related to CrowmanCloud shall not exceed the amount you paid for the software (which is currently $0 for our free version).

**Excluded Damages**: We shall not be liable for:
• Indirect, incidental, or consequential damages
• Loss of profits, data, or business opportunities
• Damages resulting from third-party actions
• Costs of substitute products or services

**Essential Purpose**: These limitations apply even if the limited remedies fail their essential purpose.

**Jurisdiction Limits**: Some jurisdictions do not allow certain limitations, so these may not apply to you.`
    },
    {
      id: "indemnification",
      title: "Indemnification",
      content: `You agree to indemnify, defend, and hold harmless CrowmanCloud, Inc., its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from:

• Your use of CrowmanCloud
• Your violation of these Terms
• Your violation of any applicable laws or regulations
• Any content or code you analyze using CrowmanCloud
• Any third-party claims related to your use of the software

This indemnification obligation survives termination of these Terms.`
    },
    {
      id: "termination",
      title: "Termination",
      content: `**Termination by You**: You may stop using CrowmanCloud at any time by uninstalling the software.

**Termination by Us**: We may terminate your license if you violate these Terms, with or without notice.

**Effect of Termination**: Upon termination:
• Your license to use CrowmanCloud ends immediately
• You must cease all use and delete all copies of the software
• Locally stored data remains under your control
• Provisions regarding liability, indemnification, and intellectual property survive

**No Refunds**: As CrowmanCloud is currently free, no refunds are applicable.`
    },
    {
      id: "governing-law",
      title: "Governing Law and Disputes",
      content: `**Governing Law**: These Terms are governed by the laws of [Your Jurisdiction], without regard to conflict of law principles.

**Dispute Resolution**: Any disputes arising from these Terms or your use of CrowmanCloud shall be resolved through:
• First, good faith negotiation between the parties
• If unsuccessful, binding arbitration under [Arbitration Rules]
• Arbitration shall be conducted in [Your Location]

**Class Action Waiver**: You agree to resolve disputes individually and waive any right to participate in class action lawsuits.

**Injunctive Relief**: Either party may seek injunctive relief in court for intellectual property violations.`
    },
    {
      id: "general",
      title: "General Provisions",
      content: `**Entire Agreement**: These Terms constitute the entire agreement between you and CrowmanCloud, Inc. regarding the software.

**Modifications**: We may update these Terms periodically. Continued use after changes constitutes acceptance of new terms.

**Severability**: If any provision is found unenforceable, the remaining provisions remain in full effect.

**No Waiver**: Our failure to enforce any provision does not waive our right to enforce it later.

**Assignment**: You may not assign your rights under these Terms. We may assign our rights with notice.

**Force Majeure**: Neither party is liable for delays or failures due to circumstances beyond reasonable control.

**Contact**: For questions about these Terms, contact us at legal@crowmancloud.com.`
    }
  ];

  return (
    <div className="terms-page">
      <div className="terms-container">
        {/* Header */}
        <div className="terms-header">
          <h1>Terms of Service</h1>
          <p className="last-updated">Last updated: {lastUpdated}</p>
          <div className="terms-summary">
            <div className="summary-card">
              <div className="summary-icon">📄</div>
              <div className="summary-content">
                <h3>Free to Use</h3>
                <p>CrowmanCloud is completely free for personal and commercial use with no hidden fees or restrictions.</p>
              </div>
            </div>
            <div className="summary-card">
              <div className="summary-icon">🔒</div>
              <div className="summary-content">
                <h3>Local-First Design</h3>
                <p>Your code stays on your machine. We have no access to your source code or intellectual property.</p>
              </div>
            </div>
            <div className="summary-card">
              <div className="summary-icon">⚖️</div>
              <div className="summary-content">
                <h3>Fair Terms</h3>
                <p>Clear, reasonable terms that protect both your rights and ours while enabling productive use.</p>
              </div>
            </div>
          </div>
        </div>

        

        

        {/* Contact Section */}
        <div className="terms-contact">
          <div className="contact-card">
            <h2>Questions About These Terms?</h2>
            <p>We believe in transparent and fair terms of service. If you have any questions about these terms or need clarification on any provision, please don't hesitate to contact us.</p>
            <div className="contact-actions">
              <a href="mailto:legal@crowmancloud.com" className="btn-primary">
                Contact Legal Team
              </a>
              <a href="mailto:crowmancloud0@gmail.com" className="btn-secondary">
                General Support
              </a>
            </div>
          </div>
        </div>

        {/* Footer Note */}
        <div className="terms-footer">
          <p>
            By using CrowmanCloud, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            These terms are designed to protect both your rights as a user and our rights as the service provider while enabling you to get the most value from CrowmanCloud.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Terms;